update linux setup for github action

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -13,19 +13,12 @@ env:
 jobs:
   build-depoly-files:
     name: Build depoly files for ${{ github.ref_name }}
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     steps:
       - name: 'Checkout'
         uses: actions/checkout@v2
         with:
           submodules: true
-      # - name: 'Checkout hoppscotch main submodules'
-      #   run: |
-      #     git checkout main
-      #     git pull
-      #     git branch
-      #     git log -n 3
-      #   working-directory: hoppscotch
       - name: 'Patch ExtensionStrategy.ts'
         run: |
           echo "original ExtensionStrategy.ts"
@@ -74,10 +67,11 @@ jobs:
     needs: [build-depoly-files]
     if: contains(github.ref, 'tags')
     strategy:
+      fail-fast: false
       matrix:
-        os: ['ubuntu-22.04', 'macos-latest', 'windows-latest']
+        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
         include:
-          - os: 'ubuntu-22.04'
+          - os: 'ubuntu-latest'
             label: 'linux'
             executable_extension: ''
           - os: 'macos-latest'
@@ -114,37 +108,41 @@ jobs:
           rustc --version
           cargo --version
       - name: 'Setup for linux'
-        if: matrix.os == 'ubuntu-22.04'
+        if: matrix.os == 'ubuntu-latest'
         run: |
           # https://ubuntu.com/blog/statement-on-32-bit-i386-packages-for-ubuntu-19-10-and-20-04-lts
           # https://askubuntu.com/questions/1252062/how-to-install-libncurses-so-5-in-ubuntu-20-04
           # https://askubuntu.com/questions/522372/installing-32-bit-libraries-on-ubuntu-14-04-lts-64-bit
-          sudo dpkg --add-architecture i386
-          sudo apt update
-          sudo add-apt-repository universe
+          # sudo add-apt-repository universe
           sudo dpkg --add-architecture i386 
           sudo apt update
           # sudo apt upgrade
           # install both 32-bit and 64-bit prerequisites of tauri
           # libayatana-appindicator3-dev is the successor of libappindicator3-dev and 64-bit only
-          # https://tauri.studio/v1/guides/getting-started/prerequisites/
-          echo install dependences ...
-          sudo apt install -y \
-            libwebkit2gtk-4.0-dev \
-            libwebkit2gtk-4.0-dev:i386 \
-            build-essential \
-            curl \
-            wget \
-            libssl-dev \
-            libssl-dev:i386 \
-            libgtk-3-dev \
-            libgtk-3-dev:i386 \
-            patchelf \
-            librsvg2-dev \
-            librsvg2-dev:i386 \
-            libayatana-appindicator3-dev \
+          # https://tauri.app/v1/guides/getting-started/prerequisites/#setting-up-linux
+          # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
+          echo install tools for 32-bit support ...
+          sudo dpkg --add-architecture i386 
+          sudo apt update
+          # sudo apt upgrade
+          sudo apt install -y --allow-downgrades \
             gcc-multilib \
             g++-multilib
+          echo install 32-bit dependences ...
+          sudo apt update
+          # sudo apt upgrade
+          sudo apt install -y --allow-downgrades \
+            libwebkit2gtk-4.0-dev:i386 \
+            libssl-dev:i386 \
+            libgtk-3-dev:i386 \
+            librsvg2-dev:i386 || echo "install 32-bit dependences failed! Check the logs for details."
+          echo install dependences ...
+          sudo apt install -y --allow-downgrades \
+            libwebkit2gtk-4.0-dev \
+            libssl-dev \
+            libgtk-3-dev \
+            librsvg2-dev \
+            libayatana-appindicator3-dev
           # use cross to build, so the dependencies are not required!
           # # check docker
           # docker -v
@@ -163,7 +161,7 @@ jobs:
           # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019
           echo 'ok'
       - name: Build Native binarys on ubuntu
-        if: matrix.os == 'ubuntu-22.04'
+        if: matrix.os == 'ubuntu-latest'
         run: |
           echo "build native binarys..."
           rustup target add x86_64-unknown-linux-gnu
@@ -249,7 +247,7 @@ jobs:
       # src-tauri/target/i686-pc-windows-msvc/release/bundle/msi/hoppscotch-app_2.1.0_x64.msi
       - name: Prepare release files on ${{matrix.label}}
         continue-on-error: true
-        if: matrix.os == 'ubuntu-22.04'
+        if: matrix.os == 'ubuntu-latest'
         run: |
           # for 64-bit binary
           mv src-tauri/target/x86_64-unknown-linux-gnu/release/${{env.APP_NAME}}${{matrix.executable_extension}} ${{env.APP_NAME}}-${{matrix.label}}-${{ github.ref_name }}_amd64${{matrix.executable_extension}}
